/**
 ** Generate the items.json file from a json file generated by Burger (https://github.com/mcdevs/Burger).
 **
 ** node gen_items.js items.json
 **
 **/

var fs = require('fs');


/**
 ** Given the path to a Burger json file, parse the file and generate a new JSON file
 **/
function gen_items(path) {
    fs.exists(path, function(exists) {
        if (!exists) {
            console.error("Invalid path %s provided.", path);
            return;
        }
        fs.readFile(path, 'utf-8', function(error, file_data) {
            var burger_json = JSON.parse(file_data);
            var item_json = burger_json[0].items.item;

            var items_by_id = {},
                items_by_name = {},
                items_by_displayname = {};

            for (var item_id in item_json) {
                var item = item_json[item_id];
                var new_item = {
                    'id': item.id,
                    'display_name': item.display_name,
                    'name': item.name,
                };
                items_by_id[item.id] = new_item;
                items_by_name[item.name] = new_item;
                items_by_displayname[item.display_name] = new_item;
            }
            var JSON_out = JSON.stringify(items_by_name, null, 4);

            fs.writeFile("items.json", JSON_out, function(err) {
                if (err) {
                    console.error("Unable to write to file.");
                    throw err;
                } else {
                    console.log("Successfully written to items.json");
                }
            });

        });
    });
}

var args = process.argv.slice(2, process.argv.length);
if (args.length <= 0) {
    console.error("No path provided.");
} else {
    gen_items(args[0]);
}